lucia-auth/lucia

- packages/lucia-sveltekit/src/client.ts
autoRefreshTokens is called after the access token expires and generates a new access and refresh token and saves it in a cookie, but it does not update the refresh token session store. When it runs again, the old refresh token is sent in the authorization header and causes handleRefreshRequest to throw REQUEST_UNAUTHORIZED since the refresh token is incorrect.
> Fix autoRefreshTokens not updating session refresh token

- apps/example-github-oauth/package.json
- apps/example-username-password/package.json
- apps/example-username-password/src/routes/__layout.svelte
- apps/example-username-password/src/routes/index.svelte
- documentation/docs/05_server-apis/index.md
- documentation/docs/09_changelog/index.md
- packages/lucia-sveltekit/package.json
- packages/lucia-sveltekit/src/Lucia.svelte
- packages/lucia-sveltekit/src/auth/request.ts
- packages/lucia-sveltekit/src/auth/session.ts
- test-apps/username-password/package.json
-   `Session.cookie` returned by `validateRequest` and `validateRequestByCookie` are the values of existing cookies instead of new cookies
-   Fixed issues with silent refresh in `Lucia.svelte` wrapper 
-   `validateRequest` and `validateRequestByCookie` returns a `Session` instead of `User`
-   Tested silent refresh in `Lucia.svelte` overnight
> update to 0.6.1

- apps/documentation/src/routes/[...doc].svelte
- apps/documentation/src/routes/api/docs/[...doc].ts
- apps/example-github-oauth/package.json
- apps/example-username-password/package.json
- documentation/docs/09_changelog/index.md
- packages/lucia-sveltekit/package.json
- packages/lucia-sveltekit/src/types.ts
- packages/lucia-sveltekit/src/utils/auth.ts
- packages/lucia-sveltekit/src/utils/token.ts
- test-apps/username-password/package.json
-   [Breaking] All tokens issued before this update is invalid
-   [Fix] `validateRequest` and `validateRequestByCookie` rejects refresh tokens
> update to 0.6.2

- .github/workflows/publish.yaml
Looks for changes in package/* dirs and auto publishes to NPM when changes detected in last commit using straightforward bash. Should be merged after package type defs are fixed for the adapters. Currently set up to auto bump minor version on change - this can be easily adjusted. 'PNPM_AUTH_TOKEN' secret must be set in Github > Repo > Settings and NPM > Repo > Settings
closes #10
> Update NPM Packages on Main Branch Push

- apps/example-username-password/README.md
- apps/example-username-password/svelte.config.js
Fixed README.md
Also, deleted lines in svelte.config.js according to https://github.com/sveltejs/kit/pull/6469 . Without this change, npm install from the example-username-password directory fails with:
> npm ERR! code 1
> npm ERR! path .../lucia-sveltekit/apps/example-username-password/node_modules/@sveltejs/kit
> npm ERR! command failed
> npm ERR! command sh /tmp/postinstall-7e2795aa.sh
> npm ERR! > Method overrides have been removed in favor of actions. See the PR for more information: https://github.com/sveltejs/kit/pull/6469
> npm ERR!     at file://.../lucia-sveltekit/apps/example-username-password/node_modules/@sveltejs/kit/src/core/config/options.js:499:10
> npm ERR!     at file://.../lucia-sveltekit/apps/example-username-password/node_modules/@sveltejs/kit/src/core/config/options. …
> Updated README.md and svelte.config.js for example

- documentation/src/pages/index.astro
You could also say "It is easy to use and understand, yet provides* the flexibility...". You most certainly don't need 2 comma's around "yet" and if you want to keep "providing the flexibility" this is probably your best bet.
> Fixes grammatical error on homepage.

- documentation/src/layouts/DocumentLayout.astro
- pnpm-workspace.yaml
Two commits:
1. Because `pnpm install` was not creating `node_modules` in documentation folder.
2. Hotfix for broken links in docs for contribution github.
For point 2:
- This solving issue #134
- Idea for variable was from PR #138
- It's not perfect solution, but working well for all scenarios for now.
- The main rootcouse is in astro implementation itself probably. But I was not able to spend more time to dig into.
- In past there was similar issue but with different method: https://github.com/withastro/astro/issues/4252
- When looking for proper fix, comment my hotfix, replace variable in path to `Astro.url.pathname` and compare contribution links in docs pages in `astro dev` with `astro build & astro preview`
Have hope this is good PR for you ;)
> Fix contribute doc link

- packages/adapter-prisma/src/index.ts
Tests passed before this change, but when I used it in my SvelteKit project, `e instanceof pkg.PrismaClientKnownRequestError` would evaluate to false even though e was an instance of `Prisma.PrismaClientKnownRequestError`.
> Use `Prisma` namespace instead of `pkg` when accessing Prisma error types

- documentation/src/components/structure/BaseLayout.astro
Currently, if the user's preferred color scheme is dark and they switch the theme to light, light mode does not persist when reloading the page or when navigating to another link and the page will switch to dark mode.
This change will use the theme from localStorage regardless of the user's preferred color scheme.
> docs: Use light theme from localStorage

- documentation/src/pages/sveltekit/api-reference/client-api.md
- packages/sveltekit/CHANGELOG.md
- packages/sveltekit/package.json
- packages/sveltekit/src/client/index.ts
- packages/sveltekit/src/client/page-data.ts
- packages/sveltekit/src/client/user.ts
- packages/sveltekit/src/load/user.ts
- packages/sveltekit/src/server/crypto.ts
- packages/sveltekit/src/server/hooks.ts
- packages/sveltekit/src/server/server-load.ts
- packages/sveltekit/src/types.ts
- test-apps/sveltekit/src/routes/+layout.svelte
- test-apps/sveltekit/src/routes/login/+page.server.ts
- [Breaking] `handleSession()` no longer sync sessions across tabs
- `handleSession()` can take an optional callback that will be called on session change
> `@lucia-auth/sveltekit`: v0.1.4

- packages/adapter-test/CHANGELOG.md
- packages/adapter-test/package.json
- packages/adapter-test/src/tests/index.ts
Currently, the `testAdapter` test suite finishes after `testUserAdapter` and does not execute the remaining tests due to the `endProcess` parameter in `testUserAdapter` defaulting to true. 
This change sets the `endProcess` parameter in `testUserAdapter` and `testSessionAdapter` to false so the entire test suite can run to completion.
Making this a draft PR since I'm not sure what you want to do for the package version.
> Fix `testAdapter` finishing before all tests are run

- documentation/src/pages/oauth/providers/twitch.md
- packages/oauth/package.json
- packages/oauth/src/twitch.ts
Accidentally left in "avatar_url" which is not a property that exists in the User response from Twitch.
> [fix] Removed "avatar_url" from TwitchUser

- packages/lucia-auth/CHANGELOG.md
- packages/lucia-auth/package.json
- packages/lucia-auth/src/auth/index.ts
- [Fix] Ignore `getSessionAndUserBySessionId()` if a normal adapter is provided as a user or session adapter
> Ignore `getSessionAndUserBySessionId()` when using normal adapters as partial adapters

- packages/lucia-auth/CHANGELOG.md
- packages/lucia-auth/package.json
- packages/lucia-auth/src/auth/index.ts
- packages/lucia-auth/src/index.ts
It is useful to have this public so end users can properly type the generic of `Auth` type.
```ts
// This is in a library. See how using `Configurations` would be nice.
export function doThing<C extends Configurations = any>(auth: Auth<C>) {}
// The rest of this code is in the users project
export const auth = lucia({
adapter: prisma(db),
env: import.meta.env.DEV ? "DEV" : "PROD",
});
doThing(auth);
```
> export `Configurations` type

- packages/sveltekit/CHANGELOG.md
- packages/sveltekit/package.json
- packages/sveltekit/src/types.ts
- [Fix] Fix `handleHooks()` types #260
> Fix `handleHooks()` types for `@lucia-auth/sveltekit`

- test-apps/sveltekit/README.md
- test-apps/sveltekit/src/routes/api/oauth/github/+server.ts
The redirect wasn't working for me. The redirect got caught in the try/catch. I fixed the problem.
I also updated the Readme in case someone wonders what the callback URL should look like without looking at the routing.
> Fix OAuth redirect for sveltekit test-app

- documentation/collection/main/reference/api/server-api.md
- packages/lucia-auth/CHANGELOG.md
- packages/lucia-auth/package.json
- packages/lucia-auth/src/auth/index.ts
Should've fixed this one earlier. Even if you needed have `Lucia.UserAttributes` defined, this was ok (now it throws an error):
```ts
await auth.createUser(provider, identifier, {})
```
Additionally, the third argument is now optional if `Lucia.UserAttributes` is empty.
- `options` parameter for `createUser()` is only necessary if `Lucia.UserAttributes` has keys
- `options.attributes` parameter for `createUser()` is only required if `Lucia.UserAttributes` has keys
> fix createUser options type

- documentation/collection/integration/oauth/reference/api-reference.md
- packages/oauth/CHANGELOG.md
- packages/oauth/package.json
- packages/oauth/src/github.ts
- packages/oauth/src/google.ts
- packages/oauth/src/index.ts
- packages/oauth/src/patreon.ts
- packages/oauth/src/reddit.ts
- packages/oauth/src/twitch.ts
- [Breaking] Rename type `GetUserType` to `LuciaUser`; remove `GetCreateUserAttributesType`
- `userAttributes` params for `createUser()` is optional if `Lucia.UserAttributes` is empty
- Make `Buffer` dependency optional
> Update OAuth package

- packages/oauth/CHANGELOG.md
- packages/oauth/package.json
- packages/oauth/src/request.ts
Hey, the GitHub API requires the User-Agent to be set.  This is not the case for all deployment environments (e.g., Cloudflare Pages Fetch API doesn't set it by default). I suggest enforcing the User-Agent as it does no harm if already provided by the environment.
> Add user-agent header to sendRequests

- documentation/collection/integration/sveltekit/api-reference/server-api.md
- documentation/collection/main/reference/configure/lucia-configurations.md
Fixed small reference documentation errors for `hash.validate` and `handleServerSession`.
> Fix reference documentation

- documentation/collection/integration/astro/start-here/quick-start.md
- documentation/collection/integration/nextjs/start-here/quick-start.md
- documentation/collection/integration/sveltekit/start-here/quick-start.md
- documentation/collection/main/reference/configure/lucia-configurations.md
Added small updates to `auth.createUser` in Astro, Next.js and SvelteKit quickstart documentation. Also added clarification on default scrypt hashing algorithm
> Updated createUser docs

- packages/sveltekit/CHANGELOG.md
- packages/sveltekit/package.json
- packages/sveltekit/src/ambient.d.ts
- packages/sveltekit/src/types.ts
Fixes #307 
- Extend type `locals` with `App.Locals`
> Extend `locals` type with `App.Locals` in SvelteKit

- packages/adapter-supabase/CHANGELOG.md
- packages/adapter-supabase/package.json
- packages/adapter-supabase/src/index.ts
- [Fix] Prevent destructuring `null`
> Fix Supabase adapter

- documentation/collection/integration/astro/start-here/quick-start.md
- documentation/collection/integration/nextjs/start-here/quick-start.md
- documentation/collection/integration/sveltekit/start-here/quick-start.md
Fix typo (`validateRequestKey()`) and make the quick start docs consistent across framework integrations.
> Fix quick start docs

- .github/workflows/publish.yaml
- documentation/collection/main/learn/start-here/getting-started.md
- package.json
As the Supabase adaptor has been dropped (#325), I thought that it might be a good idea to cleanup the rest of its references throughout the code base.
Feel free to suggest if I've missed something or if I removed something that might have been necessary.
> refactor: remove Supabase references from package

- documentation/collection/main/reference/api/server-api.md
- packages/lucia-auth/CHANGELOG.md
- packages/lucia-auth/package.json
- packages/lucia-auth/src/auth/index.ts
Fixed incorrect return type and documentation of `validateKeyPassword()`
> Fix `validateKeyPassword()` types

- .auri/$8x8cdzkj.md
- packages/integration-oauth/CHANGELOG.md
- packages/integration-oauth/package.json
This is a pull request automatically created by Auri. You can approve this pull request to update changelogs and publish packages.
- [#391](https://github.com/pilcrowOnPaper/lucia/pull/391) by [@BenocxX](https://github.com/BenocxX) : Fix the default scope for the Discord provider
> CI: Release

- documentation/collection/main/learn/basics/sessions.md
`auth.createSessionCookies` doesn't return a Promise, so nothing to await
> docs: fix wrong await

- documentation/content/main/database/prisma.md
This PR adds a section in the documentation that explains how to use the Lucia Prisma Adapter with MongoDB. Prisma is a popular ORM that supports various databases, including MongoDB.
> docs: add a how to use lucia prisma adapter with mongodb

- documentation/src/pages/[...content].astro
old:
new:
Light mode remains unchanged
> Fix dark mode heading color

- package.json
The other scripts in `package.json`, as well as the instructions in `CONTRIBUTING.md`, all use pnpm. This script produces an error whenever someone attempts to use `npm` or `yarn`.
[More info](https://pnpm.io/only-allow-pnpm)
> Only allow pnpm

- documentation/content/main/basics/keys.md
- documentation/content/main/start-here/username-password.astro.md
- documentation/content/main/start-here/username-password.nextjs.md
- documentation/content/main/start-here/username-password.sveltekit.md
- documentation/redirects.json
This should make it a bit easier to find how to implement a basic username/password
> Rename "quick start" page to "username/password example"

- documentation/content/main/start-here/getting-started.astro.md
- documentation/content/main/start-here/getting-started.md
- documentation/content/main/start-here/getting-started.nextjs.md
- documentation/content/main/start-here/getting-started.sveltekit.md
Thank you for Lucia and the stellar documentation! The prismaClient import might be missing in the SvelteKit `lucia.ts` example, unless I'm misunderstanding.
> Import prismaClient in lucia.ts

- documentation/content/oauth/start-here/getting-started.sveltekit.md
The documentation is missing the definition of the cookies method in the example, which is used to set the "github_oauth_state" in the github flow.
This PR changes:
`export const GET: RequestHandler = async () => {`
to
`export const GET: RequestHandler = async ({ cookies }) => {`
> Fix documentation: Missing Sveltekit cookies interface in requestHandler definition

- documentation/content/main/start-here/username-password.astro.md
- documentation/content/main/start-here/username-password.nextjs.md
- examples/sveltekit-email/src/lib/lucia.ts
In a couple of places on the docs and examples, incorrect frameworks were described or imported.
Only a minor thing but always good for DX
> Fix documentation: Minor clean up on docs for incorrect names/urls

- documentation/content/reference/oauth/lucia-auth-oauth.md
Link 404s since filename has changed from `index.js` to `index.ts`. This PR points the link to the directory listing.
> Fix broken link to OAuth providers integrations

- .auri/$6l1f7cok.md
- .auri/$oyjxfoxw.md
- documentation/content/main/basics/users.md
- documentation/content/reference/lucia-auth/lucia-auth.md
- examples/astro-email/package.json
- examples/astro-email/src/auth/email.ts
- examples/sveltekit-email/package.json
- examples/sveltekit-email/src/lib/email.ts
- packages/integration-tokens/package.json
- packages/integration-tokens/src/index.ts
- packages/integration-tokens/src/tokens.ts
- packages/integration-tokens/src/utils/nanoid.ts
- packages/lucia-auth/package.json
- packages/lucia-auth/src/auth/index.ts
- packages/lucia-auth/src/index.ts
- packages/lucia-auth/src/utils/crypto.ts
- packages/lucia-auth/src/utils/nanoid.ts
- test-apps/astro-email/package.json
- test-apps/astro-email/src/auth/email.ts
- test-apps/sveltekit-email/package.json
- test-apps/sveltekit-email/src/lib/email.ts
Nanoid depends on `node` native modules, and while it's possible to switch to the provided browser version, it requires some tweaking on the bundler side.
> Remove Nanoid dependency

- .auri/$prrx62g8.md
- documentation/content/reference/lucia-auth/types.md
- packages/lucia-auth/src/auth/index.ts
- packages/lucia-auth/src/auth/request.ts
- packages/lucia-auth/src/middleware/index.ts
Fixes bug where Node middleware passed the incorrect `RequestContext.request.url`
> Fix Node middleware

- documentation/content/main/start-here/username-password.nextjs.md
I found some minor mistakes in the example for nextjs username/password docs.The ```req, res``` is undefined in the code snippets when you try to use it. If you're like me, I usually copy paste docs and this fooled me for a solid 5 minutes. Ok it might be because I'm very new to Nextjs and Typescript but it wasted some time for me nonetheless. It's just so simple that I wanted to contribute. 
Great library. Easy to use. It just works especially with Prisma.
> docs: missing context in Nextjs username/password docs

- .auri/$2mwosr64.md
- packages/integration-oauth/src/providers/auth0.ts
- packages/integration-oauth/src/providers/discord.ts
- packages/integration-oauth/src/providers/facebook.ts
- packages/integration-oauth/src/providers/github.ts
- packages/integration-oauth/src/providers/linkedin.ts
Google, Patreon, Reddit and Twitch have really nice typings taking Auth as a generic param:
```ts
export declare const google: <A extends Auth<any>>(auth: A, config: Config) => {
```
```ts
const { existingUser, providerUser, createUser } = await googleAuth.validateCallback(code);
typeof existingUser == { userId: string } | null
typeof createUser == (attributes: Lucia.UserAttributes) => Promise<{ userId: string }>
```
while other providers don't:
```ts
export declare const discord: (auth: Auth, config: Config) => {
```
```ts
const { existingUser, providerUser, createUser } = await githubAuth.validateCallback(code);
typeof existingUser == any
typeof createUser == (attributes: Lucia.UserAttributes) => Promise<any>
```
So this PR fixes that by introducing the better typings (taking `Auth` as …
> Improve OAuth providers types

- documentation/content/main/adapters/drizzle.md
This small change adds the `expires` property for the `auth_key` model as it is required for authentication and it is missing from the drizzle schema.
> fix(drizzle): correct schema definition

- .auri/$fxxzlhvj.md
- .auri/$ptnjnnk9.md
- packages/adapter-mysql/package.json
- packages/adapter-sqlite/src/better-sqlite3/runner.ts
PlanetScale driver 1.7 does not work on Cloudflare workers - https://github.com/cloudflare/workers-sdk/issues/3005
Replaced `get()` with `all()` for `better-sqlite3`.
> Fix `better-sqlite3` and update Planetscale adapter peer dependency

- documentation/content/tokens/guides/two-factor-authorization.md
The change was needed because "authentication" refers to verifying identity, while "authorization" is about granting access, and 2FA is about identity verification. The change also fixes the typo "than" to "that" in the last paragraph.
> Term misusage

- documentation/content/main/basics/configuration.md
This replaces two links that lead to a 404 in the `/basics/configuration` page. Closes #593.
> Replace dead links (fixes #593)

- documentation/content/main/start-here/getting-started.md
Just to correct the usage of Express middleware in the docs, only in the Getting Started page. 
Might want to consider pointing users to `https://lucia-auth.com/reference/lucia-auth/middleware#<others>` for other usages, since the list is constantly being updated with new integrations.
> docs: fix Express usage in getting-started

- documentation/content/main/basics/keys.md
As mentioned in #610, we should remove the `const key = ` as it implies that `deleteKey()` returns a value.
> docs: fix deleteKey example

- documentation/content/main/adapters/drizzle.md
Documentation: Adapters => Drizzle ORM 
- add missing expires fields for PostgreSQL and SQLite
> [Documentation] add missing fields

- documentation/content/main/start-here/getting-started.remix.md
Thanks for the remix documentation!
I have made the following corrections.
- removed unused import
- middleware should specify web
```diff
diff --git a/documentation/content/main/start-here/getting-started.remix.md b/documentation/content/main/start-here/getting-started.remix.md
index 9405c53..5075245 100644
--- a/documentation/content/main/start-here/getting-started.remix.md
+++ b/documentation/content/main/start-here/getting-started.remix.md
@@ -35,10 +35,9 @@ In `auth/lucia.server.ts`, import [`lucia`](/reference/lucia-auth/auth) from `lu
```ts
// auth/lucia.server.ts
import lucia from "lucia-auth";
-import { nextjs } from "lucia-auth/middleware";
+import { web } from "lucia-auth/middleware";
import prisma from "@lucia-auth/adapter-prisma";
import { PrismaClient } from …
> Docs: fix getting-started.remix.md

- documentation/content/main/adapters/drizzle.md
fix Drizzle's SQLite schema
```diff
diff --git a/documentation/content/main/adapters/drizzle.md b/documentation/content/main/adapters/drizzle.md
index 81b787f..6743ac3 100644
--- a/documentation/content/main/adapters/drizzle.md
+++ b/documentation/content/main/adapters/drizzle.md
@@ -202,7 +202,7 @@ const key = sqliteTable("auth_key", {
userId: text("user_id")
.notNull()
.references(() => user.id),
-       primaryKey: integer().notNull(),
+       primaryKey: integer("primary_key").notNull(),
hashedPassword: text("hashed_password"),
expires: integer("expires")
});
```
> Docs: fix missing table in the SQLite schema at drizzle.md

- .prettierignore
- documentation/content/main/basics/handle-requests.nextjs.md
- documentation/content/main/basics/users.md
- documentation/content/main/nextjs.nextjs/app-router.md
- documentation/content/main/nextjs.nextjs/pages-router-edge.md
- documentation/content/main/start-here/getting-started.nextjs.md
- documentation/content/oauth/start-here/getting-started.nextjs.md
- examples/nextjs-app/app/api/oauth/github/route.ts
- examples/nextjs-app/lucia.d.ts
- examples/nextjs/lucia.d.ts
- test-apps/nextjs-app/app/api/oauth/github/route.ts
- test-apps/nextjs-app/lucia.d.ts
- test-apps/nextjs/lucia.d.ts
Some chore fixes:
- examples/test-apps: avoid circular request oauth token
- documents: fix typo
- format: ignore `.nuxt` path
> fix `nextjs-app` oauth examples

- documentation/content/main/start-here/username-password.sveltekit.md
"a auth method" => "an auth method"
> Tiny grammatical fix in doc

- .auri/$bdxuyuh7.md
- .auri/$n52de9fd.md
- packages/lucia/src/auth/index.ts
- packages/lucia/src/auth/request.ts
- `Auth.readSessionCookie()` takes the session header value (including `null` and `undefined`)
- `Auth.readSessionCookie()` takes the authorization header value (including `null` and `undefined`)
- New `AuthRequest.renewBearerToken()`
> Update request related methods

- documentation/content/main/start-here/username-password.sveltekit.md
Since the Auth type is defined in `$lib/server/lucia.ts` it should be imported from there, because this type in `$lib/lucia` does not exist.
> Fix imported type Auth in app.d.ts in the Username/password example

- documentation/content/main/basics/handle-requests.sveltekit.md
This fixes two issues: First, some mentions of Astro in the SvelteKit doc need to be reworked to use SvelteKit (the text is fine but the code is not). Please review these changes carefully!
Second, the example in setSession with `null` is incorrect. This fix is straightforward.
> fix docs for handle-requests.sveltekit.md

- documentation/content/main/start-here/username-password.sveltekit.md
Comma is in the wrong place.
The comma is inside a comment making it unreachable and thereby breaking the code.
Fixed! :)
> Invalid code in username-password.sveltekit.md

- .auri/$pstcxjt3.md
- packages/lucia/src/middleware/index.ts
Fixed a couple of bugs where trying to use the `auth.handleRequest()` in either a server component or API Route Handler would result in a runtime error:
```bash
- error ../packages/lucia/dist/middleware/index.js (151:46) @ get
- error TypeError: cookieStore.get is not a function
at eval (../../packages/lucia/dist/middleware/index.js:156:47)
at Auth.handleRequest (../../packages/lucia/dist/auth/index.js:340:83)
at Page (./app/page.tsx:19:71)
at async Promise.all (index 0)
149 |                 ? serverContext.cookies()
150 |                 : serverContext.cookies;
> 151 |             const sessionCookie = cookieStore.get(cookieName)?.value ?? null;
|                                              ^
152 |             const requestContext = {
153 |                 request: {
154 | …
```
> Fix `nextjs` middleware incorrect usage of `cookies` and `headers` with App Router

- documentation/content/main/start-here/getting-started.sveltekit.md
the type definition needs to be 
- import ("lucia-auth").AuthRequest so that it matches the `locals.auth.validateUser()` used in the upcoming docs.
> the type definition in the docs is incorrect

- .auri/$urcdznnh.md
- documentation-v2/content/main/2.database-adapters/unstorage.md
- examples/express/username-and-password/src/routes/logout.ts
- examples/sveltekit/email-and-password/src/routes/password-reset/[token]/+page.server.ts
- packages/lucia/src/auth/request.ts
- packages/lucia/src/auth/session.ts
- packages/lucia/src/utils/nanoid.ts
`AuthRequest.validate()` and `AuthRequest.validateBearerToken()` throws non-`LuciaError` errors (ie. database errors)
> Update `AuthRequest.validate()` and `AuthRequest.validateBearerToken()` error handling

- .auri/$ftuu9etk.md
- packages/adapter-mongoose/src/mongoose.ts
As discussed on Discord.
I've added a `getSessionAndUserBySessionId` method to the mongoose adapter, which uses a lookup (join) instead of two separate db calls.
> Add getSessionAndUserBySessionId method to adapter-mongoose

- .github/workflows/auri.yaml
- documentation/vercel.json
- Fix issues where `lucia-auth.com` isn't getting published
- Previews will always be deployed under `preview.lucia-auth.com`
> Fix Vercel deployment 

- documentation/content/guidebook/drizzle-orm/index.md
The Drizzle ORM Documentation was using `pgTable` for `sqlite`
Updated `pgTable` to `sqliteTable`
- [there is no bigint data type in SQLite](https://orm.drizzle.team/docs/column-types/sqlite#bigint) so used `blob` with `mode`
- convert `varchar` to `text`
> updated drizzle sqlite docs

- .auri/$nziehqul.md
- documentation/content/main/0.start-here/0.getting-started/fastify.md
- documentation/content/main/0.start-here/0.getting-started/nuxt.md
- documentation/content/main/0.start-here/0.getting-started/remix.md
- documentation/content/main/1.basics/5.handle-requests.md
- documentation/content/reference/lucia/2.middleware.md
- packages/lucia/package.json
- packages/lucia/src/middleware/index.ts
This is an alternate implementation for a fastify-compatible Lucia middleware. Compared to the [existing PR](https://github.com/pilcrowOnPaper/lucia/pull/589), this adds a Fastify middleware that's nearly the same as the existing Express middleware.
This _does_ add several dev dependencies to demonstrate typesafety, and does require fastify users to _also_ install @fastify-cookie. I'm not sure what kind of impact that has on the bundle size, but would appreciate feedback or other needs to add built-in fastify support to the library.
I'd also be happy to add docs similar to the exiting Express get-started if helpful.
> feat: support for fastify middleware

- documentation/src/components/menus/MainMenu.astro
Link for basics/keys was missing in the MainMenu, so I fixed.
> Add link to `Keys` in `MainMenu`

- documentation/src/components/menus/MainMenu.astro
For some reason the [Handle requests](https://lucia-auth.com/basics/handle-requests) page exists but isn't available through the main menu. This PR fixes that.
> Add link to `Handle requests` in `MainMenu`

- .auri/$q4pb9pqd.md
- documentation/content/reference/oauth/interfaces.md
- documentation/content/reference/oauth/modules/main.md
- packages/oauth/src/core.ts
- packages/oauth/src/index.ts
`decodeIdToken()` throws `SyntaxError` instead. Using `SyntaxError` is consistent with `JSON.parse()`, which throws the error if the provided JSON is malformed.
> Remove `IdTokenError`

- .auri/$xomh6zn0.md
- packages/lucia/src/auth/index.ts
- packages/lucia/src/utils/crypto.ts
Fix Lucia throwing `AUTH_OUTDATED_PASSWORD` when using Bcrypt
> Fix error when using bcrypt

- .auri/$zvzn8ngu.md
- packages/lucia/src/auth/index.ts
Fixed `updateKeyPassword()` to return a `Promise<Key>`
> Fix `updateKeyPassword()` returning `Promise<Key>`

- documentation/content/guidebook/email-verification-codes.md
> Typo in Email verification codes guidebook 

- documentation/content/guidebook/github-oauth/$astro.md
- documentation/content/guidebook/sign-in-with-username-and-password/$astro.md
In `guidebook/sign-in-with-username-and-password/astro` and `guidebook/github-oauth/astro` there was a mention of `recommended middleware` but it wasn't directly clear what was meant. It's especially confusing since `middleware` is also used as a key in the lucia-config.
I added links to the `set up middleware` header in `getting-started/astro`.
There was another mention of recommended middleware in `solidstart`'s docs, but I couldn't find the middleware-paragraph it referenced. Since it's not visible yet in the integrations-page I assume it's not yet finished.
sidenote: to test out in `dev` I had to wrap the fetch inside `utils/github` in a `try-catch`, since I don't have ur api-key.
> docs: add links to middleware-setup in astro-docs

- documentation/content/oauth/basics/oauth2-pkce.md
- documentation/content/oauth/basics/oauth2.md
- documentation/content/oauth/index.md
Correct link to oauth/basics/oauth2-pkce
> OAuth: Update documentation links

- documentation/content/main/basics/database.md
Fix links "Using Drizzle ORM" and "Using Kysely" pointing to wrong guidebook at https://lucia-auth.com/basics/database.
> docs: fix kysely and drizzle guidebook links

- documentation/content/guidebook/github-oauth/$nextjs-app.md
I believe this example was unintentionally defined as a JSX element, while it should've been just a regular html form element.
> Docs: NextJS Github OAuth <Form> -> <form> 

- documentation/content/guidebook/github-oauth/$sveltekit.md
Fixes the github-oauth login redirection file path to match with code example provided for sveltekit
> Docs: Fix sveltekit github-oauth login redirection file path

- .auri/$4yx11wwf.md
- .auri/$gmhkubg3.md
- documentation/content/oauth/index.md
- documentation/content/oauth/providers/strava.md
- documentation/content/reference/oauth/modules/providers.md
- documentation/src/components/menus/OAuthMenu.astro
- packages/oauth/src/providers/index.ts
- packages/oauth/src/providers/strava.ts
Strava provides a simple/straightforward OAuth provider, with just enough documentation to get it together. Heavily based on the Github example, obviously, this makes life a lot easier if you're one of the handful of people developing a Strava-based app.
I don't have anything resembling test coverage for this - wasn't sure where it should be - but I have tested this manually locally.
> Strava OAuth provider

- documentation/content/guidebook/email-verification-links/index.md
- documentation/content/guidebook/sign-in-with-username-and-password/$express.md
- documentation/content/guidebook/sign-in-with-username-and-password/$hono.md
- documentation/content/guidebook/sign-in-with-username-and-password/$nextjs-app.md
- documentation/content/guidebook/sign-in-with-username-and-password/$nextjs-pages.md
- documentation/content/guidebook/sign-in-with-username-and-password/$nuxt.md
- documentation/content/guidebook/sign-in-with-username-and-password/index.md
This PR fixes an issue where the `userId` assignment in the `createSession` call was incorrect in documentation. It has been updated to use `key.userId` instead of `user.userId`.
> Docs: Fix userId assignment

- .github/workflows/auri.yaml
Seems Nuxt is broken with Node 20.6 https://github.com/nuxt/nuxt/issues/23020
> Pin Node version for Github actions

- .auri/$x7ntu107.md
- packages/lucia/src/middleware/index.ts
Closes #1063 
Looks like `"request" in NextRequest` returns `true` for some reason. `Object.keys()` doesn't help either. No idea what's happening under the hood.
> Fix `Auth.handleRequest()` breaking app in Next.js middleware

- documentation/content/reference/lucia/interfaces/auth.md
The getAllUserSessions method shows getAllUserKeys instead of getAllUserSessions
> Docs: Fix function footprint for getAllUserSessions

- .auri/$mqai142h.md
- packages/adapter-session-unstorage/package.json
- packages/adapter-session-unstorage/src/unstorage.ts
Ttl support is being added to unstorage through https://github.com/unjs/unstorage/issues/262
For now the vercel-kv and redis drivers are supported, but as more support is added, this will start working for all of them.
> feat(unstorage): add ttl support

- documentation/content/oauth/index.md
- documentation/content/oauth/providers/cognito.md
- documentation/src/components/menus/OAuthMenu.astro
Changes all references of "(AWS) Cognito" to "[Amazon Cognito](https://aws.amazon.com/cognito/)" in content pages. This does not update function or method names.
> change all references of "(AWS) Cognito" -> "Amazon Cognito"

- documentation/content/oauth/index.md
- documentation/content/oauth/providers/gitlab.md
- documentation/content/reference/oauth/modules/providers.md
- documentation/src/components/menus/OAuthMenu.astro
- packages/oauth/CHANGELOG.md
Changes all references of "Gitlab" to "GitLab" in content pages. This does not update function or method names. Figured I'd update this one as well while I was in here 🙂
> change all references of Gitlab -> GitLab

- .auri/$ku1jk5lf.md
- documentation/content/oauth/basics/oauth2.md
- documentation/content/oauth/providers/apple.md
- examples/tauri/github-oauth/app/index.html
- packages/oauth/src/providers/apple.ts
Apple requires `form_post` response mode instead of `query` when requesting scopes. The `user` field is also in the callback, and not from the token endpoint.
> Fix `apple()` provider and docs

- documentation/content/main/basics/sessions.md
Fixes a minor mistake in the session documentation.
> docs: Correct link text for deleteDeadUserSessions

- documentation/content/main/getting-started/$nuxt.md
Should refer to nuxt and not next.
> docs: fix small typo in nuxt install instructions

- documentation/content/main/database-adapters/mysql2.md
The link to the mysql2 github repo is broken, as it appears the 2 was left off at the end of the link. This change fixes the link.
> Fix broken link in mysql2 database adapter page

- documentation/content/guidebook/sign-in-with-username-and-password/$astro.md
`user` was a typo in the original example. It should be `key`, just like the stackblitz-example.
> fix: error in astro-doc

- documentation/content/main/getting-started/index.md
the link to examples was pointing to a folder inside the main repo, updated it to point at eamples repo
> docs: update examples link

- documentation/content/main/getting-started/$astro.md
- documentation/content/main/getting-started/$elysia.md
- documentation/content/main/getting-started/$express.md
- documentation/content/main/getting-started/$fastify.md
- documentation/content/main/getting-started/$hono.md
- documentation/content/main/getting-started/$nextjs-app.md
- documentation/content/main/getting-started/$nextjs-pages.md
- documentation/content/main/getting-started/$nuxt.md
- documentation/content/main/getting-started/$remix.md
- documentation/content/main/getting-started/$solidstart.md
- documentation/content/main/getting-started/$sveltekit.md
- documentation/content/main/getting-started/index.md
This PR updates the old examples link in the main Lucia repo to the new examples repository.
> docs: fix examples repository link

- documentation/content/guidebook/github-oauth/$nextjs-app.md
I try to follow this guidebook https://lucia-auth.com/guidebook/github-oauth/nextjs-app/ to integrate my nextjs app with github oauth. I copy all code example in guide book but i get this error `Cannot find name 'cookies'. Did you mean 'Cookies'?`. It's turns out there is a typo on this code example
```ts
// app/login/github/route.ts
import { auth, githubAuth } from "@/auth/lucia";
import * as context from "next/headers";
import type { NextRequest } from "next/server";
export const GET = async (request: NextRequest) => {
const [url, state] = await githubAuth.getAuthorizationUrl();
// store state 
cookies().set("github_oauth_state", state, {
httpOnly: true,
secure: process.env.NODE_ENV === "production",
path: "/",
maxAge: 60 * 60
});
// typo here ^ Cannot find name 'cookies'. Did you mean …
```
> fix code example on github oauth in nextjs app router guidebook

- documentation/content/oauth/providers/slack.md
To reflect changes made in #1147 
Not sure if this needs a changeset since this is a documentation change?
> Fix default Slack scopes in documentation

- documentation/content/main/basics/fallback-database-queries.md
I followed this document using prisma transaction and I had to add the `await` keyword before `generateLuciaPasswordHash(password)` as in:
```
await tx.proKey.create({
select: {
id: true
},
data: {
id: createKeyId('email', email),
user_id: user.id,
hashed_password: await generateLuciaPasswordHash(password)
}
})
```
> fix(doc): await missing in example

- documentation/content/main/basics/sessions.md
In the code example of `the Auth.getSessions()` API, the `Auth.validateSession()` has been called by mistake.
> Fixed validateSession called instead of getSessions

- .auri/$avmnsr2u.md
- documentation/content/oauth/providers/gitlab.md
- packages/oauth/src/providers/gitlab.ts
Add new `serverUrl` param to provide the URL of a self-managed GitLab instance. 
Closes #1228
> Add "serverUrl" param to GitlabAuth config

- .auri/$4u4hf1ka.md
- documentation/content/oauth/providers/keycloak.md
- packages/oauth/src/core/oauth2.ts
- packages/oauth/src/providers/index.ts
- packages/oauth/src/providers/keycloak.ts
This Adds Keycloak as a new provider.
-> Added Keycloak.ts and updated index.ts
As this is a self-hosted provider, following settings need to be set:
keycloakClientId: "`ClientId`",
keycloakClientSecret: "`ClientSecret`",
keycloakAuthEndpoint: "https://`domain`/realms/`realm`/protocol/openid-connect/auth",
keycloakTokenEndpoint: "https://`domain`/realms/`realm`/protocol/openid-connect/token",
keycloakUserinfoEndpoint: "https://`domain`/realms/`realm`/protocol/openid-connect/userinfo",
authRedirectUri: "`url to callback`"
> Adds Keycloak Provider

- documentation/content/guidebook/drizzle-orm.md
- documentation/content/main/basics/database.md
I think this is a typo for the [`@neondatabase/serverless`](https://github.com/neondatabase/serverless) package
> docs: @neonserverless/database to @neondatabase/serverless

- documentation/src/pages/database/sqlite.md
Removed the duplicated "PRIMARY KEY" declaration from the session table migration for SQLite.
> fix: session migration

- .auri/$usr71dkt.md
- packages/lucia/src/middleware/index.ts
Fixes #1300 by adding a default `path: '/'` to all cookies set through the SvelteKit middleware.
I don't love the shallow copy of the cookie attributes to add a default path, but I think it's better than an explicit cast, like:
```typescript
cookie.attributes.path ??= '/';
event.cookies.set(cookie.name, cookie.value, cookie.attributes as CookieAttributes & { path: string });
```
> Add default cookie path for SvelteKit

- documentation/content/reference/lucia/interfaces/auth.md
The example for `auth.transformDatabaseUser` incorrectly uses `auth.transformDatabaseSession` instead of `auth.transformDatabaseUser`.
> fix: use transformDatabaseUser in transformDatabaseUser example

- packages/lucia/src/core.ts
This fixes an issue where the `getSessionAttributes` is not passed the correct raw DB attributes when called in `getUserSessions`.
Also thought this was such a small fix that an issue might not be needed (nor this PR to be honest, but it's a slow wednesday evening), if you'd prefer an issue linked to it just let me know.
> Fix session attributes when getting all user sessions

- packages/oauth/src/providers/dropbox.ts
Dropbox has moved it token endpoint to their api domain and put the current account info behind a POST request
> Fix dropbox provider

- docs/pages/tutorials/username-and-password/sveltekit.md
There is a line of text that has been added to a table cell by accident
This should be a new paragraph under the table, which this MR moves it to.
> Fix SvelteKit docs line of text in a cell

- docs/pages/guides/validate-session-cookies/sveltekit.md
- docs/pages/tutorials/github-oauth/sveltekit.md
- docs/pages/tutorials/username-and-password/sveltekit.md
Updated documentation to align with SvelteKit 2's redirect syntax. Changes involve simplifying the redirect command by removing the `throw` statement.
- Modified redirect command in 3 files:
- Replaced `throw redirect("/login");` with `redirect("/login");`.
> (V3) Update docs to use SvelteKit 2 redirect

- .auri/$ygs60su4.md
- packages/oauth/src/providers/atlassian.ts
Now using the correct endpoint to exchange the authorization code.
Closes #1352
> Fix Atlassian provider

- .auri/$e3mj84c4.md
- packages/lucia/src/crypto.test.ts
- packages/lucia/src/crypto.ts
Fixes #1369 .
Hashes were supposed to include an `s2:` prefix but didn't. If you are using v3 in production, please add a `s2:` prefix to all hashes generated post v2. (e.g. `s2:aaaaaa:bbbbbbbbbb`)
Adds test to prevent the same issue from appearing
> Fix `LegacyScrypt`

- docs/pages/database/mongoose.md
The provided example had a typo and was attempting to import an inexistent artefact.
> Update mongoose.md with fixed typo

- docs/pages/guides/oauth/multiple-providers.md
There is a small type in the multiple oauth providers guide.
When inserting into the user table, it should be githubUser.login and not github.login.
> typo: should be githubUser.login and not github.login

- packages/adapter-drizzle/src/drivers/mysql.ts
- packages/adapter-drizzle/src/drivers/postgresql.ts
- packages/adapter-drizzle/src/drivers/sqlite.ts
DrizzleORM has [Partial Select API](https://orm.drizzle.team/docs/joins#partial-select) so it's very easy to get session and user in one database query.
<details>
<summary>Simple example how it works</summary>
```ts
import { eq, sql } from 'drizzle-orm';
import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import sqlite from 'better-sqlite3';
const userTable = sqliteTable('user', {
id: text('id').notNull().primaryKey(),
username: text('username').notNull(),
});
const sessionTable = sqliteTable('session', {
id: text('id').notNull().primaryKey(),
userId: text('user_id')
.notNull()
.references(() => userTable.id),
expiresAt: integer('expires_at').notNull(),
});
const sqliteDb = sqlite(':memory:');
const db = …
```
> fix(adapter-drizzle): get session and user in one query

- docs/pages/database/mongodb.md
On the mongodb database doc there's a spelling/case mistake.
Under Usage the MongodbAdapter was using the wrong import.
> Fix wrong import for MongodbAdapter in mongodb database doc

- docs/pages/tutorials/index.md
Hi @pilcrowOnPaper,
Please kindly check it out later. \
Thank you! 
Note:
- Fixed link not properly added to the Tutorials page (should be **Next.js Pages/App router** instead of **Next.js**).
- Additionally, also reordering the list to matched like the others.
Attachments:
- Wrong link and list for Next.js.
- Matched the order list.
> Resolve (docs) "Fixed Broken 404 Page Lucia Auth Tutorials for Next.js"

- docs/pages/guides/oauth/account-linking.md
As per the GitHub [documentation](https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#user-agent-required):
_"Requests without a valid User-Agent header will be rejected. You should use your username or the name of your application for the User-Agent value"_
I was following the account-linking example in the documentation and kept getting statuscode 403 without the `User-Agent` header.
> [DOCS] Update Github OAuth guide to contain 'User-Agent' in fetch header

- packages/adapter-drizzle/src/drivers/mysql.ts
- packages/adapter-drizzle/src/drivers/postgresql.ts
- packages/adapter-drizzle/src/drivers/sqlite.ts
In the signature of the DrizzleSQLiteAdapter constructor, the generic type TFullSchema of BaseSQLiteDatabase was not set. Consequently, an instance with a schema couldn't be passed.
<details>
<summary>example</summary>
```ts
import { DrizzleSQLiteAdapter } from "@lucia-auth/adapter-drizzle";
import { Database } from "bun:sqlite";
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { drizzle } from "drizzle-orm/bun-sqlite";
const sqliteDB = new Database(":memory:");
const userTable = sqliteTable("user", {
id: text("id").notNull().primaryKey(),
});
const sessionTable = sqliteTable("user_session", {
id: text("id").notNull().primaryKey(),
userId: text("user_id")
.notNull()
.references(() => userTable.id),
expiresAt: integer("expires_at").notNull(),
});
const db = …
```
> Fix DrizzleSQLiteAdapter constructor signature

- docs/pages/getting-started/sveltekit.md
- docs/pages/upgrade-v3/index.md
Added specific configuration example for Svelte/Kit
I am not sure exactly what to include, since I tested only for `sveltekit` with `adapter-node` specifically.
I couldn't `build` successfully until I moved `oslo` from `devDependencies` to `dependencies`. I tried with `optimizeDeps: { exclude: ["oslo"] }` before, but it did not solve my issue. The `vite build` process could succeed, but then the `@sveltejs/adapter-node` step would fail.
Here's the stack in case someone have the same problem :
```
> Using @sveltejs/adapter-node
error during build:
RollupError: Unexpected character '\u{7f}'
at error (file:///home/$USER/sveltekit-demo/node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
at parseError …
```
> Update index.md - Added specific configuration example for Svelte/Kit

- docs/pages/tutorials/github-oauth/nextjs-app.md
- packages/adapter-postgresql/CHANGELOG.md
The ActionResult interface isn't included in the docs. It might be confusing given that it is used in the example project.
https://github.com/lucia-auth/examples/blob/main/nextjs-app/github-oauth/app/page.tsx
> [DOCS]: Include ActionResult interface in nextjs github-oath tutorial

- docs/pages/tutorials/username-and-password/sveltekit.md
The SvelteKit tutorial for username and password auth links to the Astro getting started page. This PR updates it to the SvelteKit one.
> Fix getting started link in SvelteKit username and password tutorial

- docs/pages/guides/oauth/custom-providers.md
I think it is supposed to be `refreshAccessToken`.
> docs(custom-providers): correct method name

- packages/adapter-drizzle/src/drivers/mysql.ts
- packages/adapter-drizzle/src/drivers/postgresql.ts
- packages/adapter-drizzle/src/drivers/sqlite.ts
Fix type error when user ID is numeric in Drizzle adapter
ref: #1472
> Fix missing userId type in `@lucia-auth/adapter-drizzle`

- packages/adapter-drizzle/src/drivers/sqlite.ts
This fix allows userId to be a number if `UserId` is registered as a number when using drizzle sqlite adapter.
In drizzle postgres and mysql adapters, the `dataType` is already `any` while `data` is `UserId`.
> Allow userId in session table in sqlite drizzle adapter to be number

- docs/pages/guides/validate-session-cookies/hono.md
There was a type error where middlewares needed to be async and `getCookie` expects `context` as first argument.
> docs: update session cookie validation docs for hono

- docs/pages/guides/email-and-password/2fa.md
- docs/pages/guides/email-and-password/email-verification-codes.md
- docs/pages/guides/email-and-password/email-verification-links.md
- docs/pages/guides/oauth/account-linking.md
The examples don't pass a param to `generateId()`, which leads to an empty returned string.
> docs: fix typo

- docs/pages/tutorials/github-oauth/sveltekit.md
Using `import.meta.env` returns `undefined`
> docs: fix undefined sveltekit env vars

- docs/pages/guides/validate-session-cookies/hono.md
just a documentation update.
updating hono guide to use the built-in hono/csrf middleware, see https://hono.dev/middleware/builtin/csrf
> docs: using hono/csrf middleware

- docs/pages/database/sqlite.md
Currently, docs for SQLite at [https://lucia-auth.com/database/sqlite](https://lucia-auth.com/database/sqlite) shows a description under LibSQL as:
`LibSQLAdapter takes a D1Database instance and a list of table names.`
However, we pass a Client instance to it.
https://github.com/lucia-auth/lucia/blob/d285a08dc2eda428236a1b267b19c01886e786ad/packages/adapter-sqlite/src/drivers/libsql.ts#L7C18-L7C24
This PR fixes it.
> docs: correct instance name passed to LibSQLAdapter

- packages/adapter-drizzle/package.json
Mark drizzle-orm as a peer dep so you don't get type issues when using the adapters that have different versions of drizzle-orm specified.
> chore(adapter-drizzle): mark drizzle-orm as a peer dependency

- docs/pages/basics/users.md
This fixes what I believe was a small copy/paste typo that gave me a quick second of confusion while working through the docs.
The section is "Define user attributes" and the first sentence describes defining custom session attributes.
> docs: fix typo in custom user attributes docs

- docs/pages/tutorials/username-and-password/nextjs-app.md
In the signup process, we used "password_hash". However, during sign-in, we are using "password" for the same table, but this column does not exist in the example.
> fix docs example app router

- docs/pages/tutorials/username-and-password/astro.md
> Fix missing `generateIdFromEntropySize()` import in Astro tutorial

- docs/pages/getting-started/astro.md
- docs/pages/guides/validate-session-cookies/astro.md
Closes https://github.com/lucia-auth/lucia/issues/1585
Uses the newly added `security.checkOrigin` config
https://docs.astro.build/en/reference/configuration-reference/#security
> Docs: Update Astro CSRF protection

- docs/pages/guides/email-and-password/email-verification-links.md
- docs/pages/guides/email-and-password/password-reset.md
Using `no-referrer` blocks the browser from sending the `Origin` header as well
> Use `strict-origin` referrer policy

- docs/pages/guides/validate-session-cookies/express.md
In the code sample for validating session in express, before validating there is a middleware that verify the request origins. However, in that middleware, once every is verified and valid for an non-GET request, it forgets to return the value of the next function. Without this, any non-GET requests that has valid request origins will stall.
> docs: fix code sample for validating sessions in express.

- docs/pages/tutorials/username-and-password/nextjs-pages.md
"pages/api/signup.ts" should be "pages/api/login.ts" to match the intended code snippet.
> Docs: fix typo to match file name to code example

- docs/pages/database/drizzle.md
- packages/adapter-drizzle/tests/sqlite.ts
SQLite applies not null constraint automatically for primary key rows and so not null is redundant. 
Drizzle supports this behavior for SQLite, PG, and MySQL - https://orm.drizzle.team/docs/indexes-constraints#primary-key
Removed redundant instance of notNull() in context of primaryKey(), from docs and adapter to better match existing PG and MySQL examples. 
(This is my first PR so unsure if this is useful / appropriate.)
> Removing redundant not nulls from primary key rows for drizzle/sqlite docs and adapter

- docs/pages/guides/validate-session-cookies/nextjs-app.md
- docs/pages/tutorials/github-oauth/nextjs-app.md
- docs/pages/tutorials/username-and-password/nextjs-app.md
This PR updates the terminology in the Next.js App Router documentation from "API Routes" to "Route Handlers". This change aligns the documentation with the current Next.js terminology, improving clarity and consistency for users implementing authentication with the App Router.
- Updated the following files:
1. `nextjs-app.md` (Validate session cookies guide)
2. `nextjs-app.md` (GitHub OAuth guide)
3. `nextjs-app.md` (Username and password auth guide)
- Replaced all instances of "API Routes" with "Route Handlers"
Before:
```markdown
Create an API routes in `app/login/github/route.ts`.
```
After:
```markdown
Create a Route Handlers in `app/login/github/route.ts`.
```
The current documentation uses outdated terminology from the Pages Router, which may confuse users implementing …
> Update "API Routes" to "Route Handlers" in Next.js App Router documentation

- pages/sessions/basic-api/drizzle-orm.md
Drizzle-ORM Basic API documentation page incorrectly uses type `void` for `async` function in the implementation of `invalidateSession`. However, it is correctly noted as `Promise<void>` above; this PR simply changes the type to match the previous type and include code which can compile.
> docs: fix Promise<void> type for async invalidateSession in DrizzleORM docs

- pages/sessions/cookies/nextjs.md
- pages/tutorials/github-oauth/nextjs.md
- pages/tutorials/google-oauth/nextjs.md
As of Next.js 15, the `cookies()` API is now asynchronous (see [release notes](https://nextjs.org/blog/next-15#async-request-apis-breaking-change) and [upgrade guide](https://nextjs.org/docs/app/building-your-application/upgrading/version-15#async-request-apis-breaking-change)). This PR updates the guide to reflect these changes.
Please let me know if there are any questions or if I need to change anything.
> Update Next.js: Refactor to Asynchronous `cookies()` API

- pages/sessions/cookies/astro.md
The value of security.checkOrigin should be 'true' to enable CSRF protection. This seems to be a typo in the docs.
> docs: typo in astro csrf protection codeblock

- pages/sessions/basic-api/postgresql.md
There was an error with the validSessionToken function where to update the expiresAt property of the session in the database, the code was converting the date object to a number and even that without using .getTime(). I fixed that by removing unnecessary conversions.
> fix updated expiresAt in validateSessionToken

- pages/sessions/basic-api/prisma.md
- All async functions return promises
- `db` was written in place of `prisma` in one example
> Docs: Prisma example return types and var names

- pages/sessions/basic-api/drizzle-orm.md
Fixing the return type of an async function that is missing a `Promise<>`.
> fix: incorrect return type

- pages/sessions/basic-api/drizzle-orm.md
- pages/sessions/basic-api/mysql.md
- pages/sessions/basic-api/postgresql.md
- pages/sessions/basic-api/prisma.md
- pages/sessions/basic-api/redis.md
- pages/sessions/basic-api/sqlite.md
The purpose of this function is to allow invalidation of all active sessions for a given user.
tasks:
> feat: Implement invalidateAllSessions function in Basic API

- pages/rate-limit/token-bucket.md
The bucket code probably wasn't changed accordingly when someone added the interface for the bucket object.
> fix: bucket object key not matching the bucket interface type
