lucia-auth/lucia

- apps/documentation/.gitignore
- apps/documentation/package.json
- apps/documentation/src/routes/api/docs/[...doc].ts
- apps/documentation/svelte.config.js
Dependency to `jsdom` causes an error on Vercel deploy. Moved to `node-html-parser`.
- #4
> Move to Vercel's edge network

- apps/example-password-oauth/README.md
Original readme had broken link
> fixes link in oauth-example README

- documentation/docs/03_adapters/prisma.md
- documentation/docs/03_adapters/supabase.md
- documentation/docs/05_server-apis/index.md
- documentation/docs/08_references/instances.md
- documentation/docs/08_references/types.md
- packages/adapter-prisma/.env
- packages/adapter-prisma/.gitignore
- packages/adapter-prisma/README.md
- packages/adapter-prisma/package.json
- packages/adapter-prisma/src/index.ts
- packages/adapter-prisma/tsconfig.json
- packages/adapter-supabase/src/index.ts
- packages/lucia-sveltekit/package.json
- packages/lucia-sveltekit/src/app.d.ts
- packages/lucia-sveltekit/src/auth/endpoints/logout.ts
- packages/lucia-sveltekit/src/auth/index.ts
- packages/lucia-sveltekit/src/auth/request.ts
- packages/lucia-sveltekit/src/auth/token.ts
- packages/lucia-sveltekit/src/auth/user/authenticate.ts
- packages/lucia-sveltekit/src/auth/user/create.ts
- packages/lucia-sveltekit/src/auth/user/get.ts
- packages/lucia-sveltekit/src/types.ts
- packages/lucia-sveltekit/src/utils/auth.ts
- packages/lucia-sveltekit/src/utils/token.ts
Tested adapter with PlanetScale/MySQL. Better TS support allowing users to define and access types of `user_data`.
> Add adapter for Prisma and better TypeScript support

- documentation/docs/02_getting-started/index.md
- documentation/docs/03_adapters/custom.md
- documentation/docs/03_adapters/prisma.md
- documentation/docs/03_adapters/supabase.md
- /adapters/custom: Fix types
- /getting-started: Added explanation for hooks, fixed syntax
- /adapters/prisma: Fixed code, added explanation for `[user_data]`
- /adapters/supabase: added explanation for `[user_data]`
- #13
> Fix documentation

- packages/adapter-prisma/package.json
- packages/adapter-prisma/src/index.ts
> fix types import

- apps/documentation/src/lib/format.ts
- documentation/docs/03_adapters/appwrite.md
- documentation/docs/03_adapters/custom.md
- documentation/docs/03_adapters/mongodb.md
- documentation/docs/03_adapters/prisma.md
- packages/adapter-appwrite/.gitignore
- packages/adapter-appwrite/README.md
- packages/adapter-appwrite/package.json
- packages/adapter-appwrite/src/index.ts
- packages/adapter-appwrite/test/index.ts
- packages/adapter-appwrite/tsconfig.json
- packages/adapter-prisma/package.json
- packages/adapter-supabase/package.json
- packages/adapter-test/package.json
- packages/adapter-test/src/index.ts
- Adds support to Appwrite's document database with a new adapter.
- Fixed typo in `adapter-test`
> New AppWrite adapter

- apps/example-github-oauth/src/routes/api/github.ts
- documentation/docs/03_adapters/custom.md
- documentation/docs/03_adapters/index.md
- documentation/docs/07_guides/oauth.md
Closes https://github.com/pilcrowOnPaper/lucia-sveltekit/issues/29
> Fix typo with user_id param and `unique`

- documentation/docs/03_adapters/appwrite.md
- documentation/docs/03_adapters/mongoose.md
- documentation/docs/03_adapters/prisma.md
- documentation/docs/03_adapters/supabase.md
This PR adds a "installation" section to each adapter's doc
> Add "installation" section to adapter docs

- documentation/docs/02_getting-started/index.md
- Add missing imports in examples to prevent confusion
- Fix `handleLoad` import as it was wrong
> Various docs fixes

- documentation/docs/02_getting-started/index.md
I _think_ this is the only place you directly reference the lucia.ts file name.
> Oops! Overzealous rename

- documentation/src/pages/learn/basics/get-current-user-in-the-client.md
- documentation/src/pages/learn/start-here/getting-started.md
Add missing semicolons to solve deviations on the "Get started" page
> Add missing semicolons

- documentation/src/components/BaseLayout.astro
Small fix for proper display your beautiful favicon in docs ;)
> add favicon link path

- documentation/src/pages/learn/adapters/supabase.md
> fix missing comma

- examples/sveltekit/username-password-supabase/src/routes/+page.ts
- packages/sveltekit/CHANGELOG.md
- packages/sveltekit/package.json
- packages/sveltekit/src/client/index.ts
- test-apps/sveltekit/src/routes/+layout.svelte
- test-apps/sveltekit/src/routes/+page.ts
- test-apps/sveltekit/src/routes/about/+page.svelte
- test-apps/sveltekit/src/routes/login/+page.ts
- Resolve issue where `handleSession()` was throwing error on pages without `getUser()` in the load function [#182](https://github.com/pilcrowOnPaper/lucia-auth/issues/182#issuecomment-1296033717)
> `@lucia-auth/sveltekit`: v0.1.3

- packages/oauth/package.json
Forgot to add twitch as an export in `package.json` 😅
> [Fix] added twitch to package.json exports

- packages/oauth/package.json
Reverts pilcrowOnPaper/lucia-auth#207
> Revert "[Fix] added twitch to package.json exports"

- packages/adapter-mongoose/CHANGELOG.md
- packages/adapter-mongoose/package.json
- packages/adapter-mongoose/src/index.ts
- [Fix] Remove `instance of` check for error #213
> `adapter-mongoose` v0.1.4

- documentation/src/pages/learn/adapters/kysely.md
- packages/adapter-kysely/.gitignore
- packages/adapter-kysely/.npmignore
- packages/adapter-kysely/.prettierignore
- packages/adapter-kysely/CHANGELOG.md
- packages/adapter-kysely/README.md
- packages/adapter-kysely/package.json
- packages/adapter-kysely/src/dbTypes.ts
- packages/adapter-kysely/src/index.ts
- packages/adapter-kysely/src/t.d.ts
- packages/adapter-kysely/src/utils.ts
- packages/adapter-kysely/test/db.ts
- packages/adapter-kysely/test/index.ts
- packages/adapter-kysely/test/userid.ts
- packages/adapter-kysely/tsconfig.json
Adds an adapter for [Kysely query builder](https://github.com/koskimas/kysely).
> [feat] Add adapter for Kysely query builder

- .eslintrc.cjs
- .github/workflows/publish.yaml
- packages/sveltekit/CHANGELOG.md
- packages/sveltekit/package.json
- packages/sveltekit/src/server/hooks.ts
- pnpm-workspace.yaml
> `@lucia-auth/sveltekit` 0.3.1

- .eslintrc.cjs
- packages/adapter-supabase/CHANGELOG.md
- packages/adapter-supabase/package.json
- packages/adapter-supabase/src/index.ts
- pnpm-workspace.yaml
- [Fix] Update Postgrest result type #223 
- Update dependencies
> `@lucia-auth/adapter-supabase` 0.1.4

- documentation/src/pages/oauth/providers/github.md
- documentation/src/pages/oauth/providers/google.md
- documentation/src/pages/oauth/providers/twitch.md
- documentation/src/pages/oauth/reference/api-reference.md
- documentation/src/pages/oauth/start-here/getting-started.md
- examples/astro/src/pages/api/logout.ts
- examples/oauth/src/pages/api/github.ts
- examples/oauth/src/pages/api/google.ts
- examples/oauth/src/pages/api/logout.ts
- examples/oauth/src/pages/index.astro
- packages/oauth/CHANGELOG.md
- packages/oauth/package.json
- packages/oauth/src/github.ts
- packages/oauth/src/google.ts
- packages/oauth/src/index.ts
- packages/oauth/src/twitch.ts
- test-apps/astro/src/pages/api/logout.ts
- test-apps/oauth/src/pages/api/github.ts
- test-apps/oauth/src/pages/api/google.ts
- test-apps/oauth/src/pages/api/logout.ts
- test-apps/oauth/src/pages/index.astro
Leaving as a draft so I don't forget to update the following:
> added state as an optional query param for oauth

- documentation/src/pages/oauth/providers/patreon.md
- package.json
- packages/adapter-kysely/package.json
- packages/adapter-mongoose/package.json
- packages/adapter-prisma/package.json
- packages/adapter-supabase/package.json
- packages/adapter-test/package.json
- packages/astro/package.json
- packages/express/package.json
- packages/lucia-auth/package.json
- packages/nextjs/package.json
- packages/oauth/package.json
- packages/oauth/src/patreon.ts
- packages/session-adapter-redis/package.json
- packages/sveltekit/package.json
Implement Patreon OAuth as a Provider.
> Patreon oauth

- package.json
- packages/lucia-auth/CHANGELOG.md
- packages/lucia-auth/package.json
- packages/lucia-auth/src/auth/index.ts
- [Fix] Get proper types for `User`
> `lucia-auth` 0.3.0

- documentation/content/oauth/providers/reddit.md
- packages/oauth/CHANGELOG.md
- packages/oauth/package.json
- packages/oauth/src/reddit.ts
- packages/oauth/src/request.ts
PR to add Reddit OAuth package.
I hope this time my code formatting is better :)
I tested the package successfully with the sveltekit test-app.
> Add Reddit OAuth package

- documentation/content/learn/adapters/fauna.md
- packages/adapter-fauna/CHANGELOG.md
- packages/adapter-fauna/README.md
- packages/adapter-fauna/package.json
- packages/adapter-fauna/src/index.ts
Reading through the Fauna doc I just found the solution for the auto user id generation.
No hurry on merging this PR :)
> Add auto user id generation to fauna adapter

- packages/adapter-prisma/CHANGELOG.md
- packages/adapter-prisma/package.json
- packages/adapter-prisma/src/index.ts
- packages/adapter-prisma/src/utils.ts
Oops!
- [Fix] Remove minor breaking change introduced in `0.2.1`
> Remove breaking change introduced in Prisma adapter `0.2.1`

- documentation/src/lib/state.ts
- documentation/src/pages/[integration]/[...path].astro
> Fix menu button

- packages/lucia-auth/CHANGELOG.md
- packages/lucia-auth/package.json
- packages/lucia-auth/src/auth/index.ts
- packages/oauth/CHANGELOG.md
- packages/oauth/README.md
- packages/oauth/package.json
- packages/oauth/src/github.ts
- packages/oauth/src/google.ts
- packages/oauth/src/patreon.ts
- packages/oauth/src/reddit.ts
- packages/oauth/src/request.ts
- packages/oauth/src/twitch.ts
- Expose `ENV` 
- [Breaking] Require `lucia-auth` 0.4.3+
- Log request errors on dev mode
> Log OAuth request error on dev mode

- packages/adapter-mongoose/CHANGELOG.md
- packages/adapter-mongoose/README.md
- packages/adapter-mongoose/package.json
- packages/adapter-mongoose/src/index.ts
- [Fix] Fix error handling error
> Fix Mongoose error handling

- documentation/src/pages/index.astro
> Optimize contributor avatar images

- documentation/collection/main/learn/adapters/mongoose.md
- documentation/collection/main/learn/adapters/prisma.md
- documentation/collection/main/reference/api/server-api.md
What this pull request does is to add some examples and notes in the Prisma and Mongoose adapters section.
My intention is to make it easier for new users to understand how Lucia works.
> docs: add some examples and notes in the docs

- documentation/collection/integration/sveltekit/start-here/getting-started.md
- documentation/collection/main/learn/adapters/kysely.md
- documentation/collection/main/learn/adapters/mongoose.md
- documentation/collection/main/learn/adapters/prisma.md
- documentation/collection/main/learn/adapters/redis.md
- documentation/collection/main/learn/basics/error-handling.md
- documentation/collection/main/learn/basics/keys.md
- documentation/collection/main/learn/basics/sessions.md
- documentation/collection/main/learn/basics/user-attributes.md
- documentation/collection/main/learn/basics/users.md
- documentation/collection/main/learn/start-here/getting-started.md
- documentation/collection/main/learn/start-here/introduction.md
A couple of suggestions to make the Lucia documentation even better. Thanks a lot by the way for creating this library, my gratitude is beyond words.
> Docs update

- documentation/src/pages/index.astro
> Update docs for 0.7.0

- .auri/$2wrh8gsj.md
- .auri/$5xvwbheq.md
- .auri/$96t7sw96.md
- .auri/$c32wsc8h.md
- .auri/$d4mxr4wy.md
- .auri/$jdf3rjla.md
- .auri/$k2bripao.md
- .auri/$kbyb1hy9.md
- .auri/$kvrvn0b2.md
- .auri/$l6p5dh4h.md
- packages/adapter-kysely/package.json
- packages/adapter-mongoose/package.json
- packages/adapter-prisma/package.json
- packages/adapter-session-redis/package.json
- packages/adapter-test/package.json
- packages/integration-astro/package.json
- packages/integration-nextjs/package.json
- packages/integration-oauth/package.json
- packages/integration-sveltekit/package.json
- packages/lucia-auth/package.json
`node_modules` was getting included on release
> Fix publish command

- package.json
- packages/adapter-kysely/.npmignore
- packages/adapter-kysely/package.json
- packages/adapter-mongoose/.npmignore
- packages/adapter-mongoose/package.json
- packages/adapter-prisma/package.json
- packages/adapter-session-redis/.npmignore
- packages/adapter-session-redis/package.json
- packages/adapter-test/.npmignore
- packages/adapter-test/package.json
- packages/integration-astro/.npmignore
- packages/integration-astro/package.json
- packages/integration-nextjs/.npmignore
- packages/integration-nextjs/package.json
- packages/integration-oauth/.npmignore
- packages/integration-oauth/package.json
- packages/integration-sveltekit/.npmignore
- packages/integration-sveltekit/package.json
- packages/lucia-auth/.npmignore
- packages/lucia-auth/package.json
> Update publish script

- .auri/$1ralw87f.md
- .auri/$4s6nnca3.md
- .auri/$9mc5j6b0.md
- .auri/$fukkj7hv.md
- .auri/$hgkigkt5.md
- .auri/$igjf9xyh.md
- .auri/$p6xnrm7z.md
- .auri/$teimhwuy.md
- .auri/$v8i2yj4o.md
- .auri/$wins3y4i.md
- packages/adapter-kysely/CHANGELOG.md
- packages/adapter-kysely/package.json
- packages/adapter-mongoose/CHANGELOG.md
- packages/adapter-mongoose/package.json
- packages/adapter-prisma/CHANGELOG.md
- packages/adapter-prisma/package.json
- packages/adapter-session-redis/CHANGELOG.md
- packages/adapter-session-redis/package.json
- packages/adapter-test/CHANGELOG.md
- packages/adapter-test/package.json
- packages/integration-astro/CHANGELOG.md
- packages/integration-astro/package.json
- packages/integration-nextjs/CHANGELOG.md
- packages/integration-nextjs/package.json
- packages/integration-oauth/CHANGELOG.md
- packages/integration-oauth/package.json
- packages/integration-sveltekit/CHANGELOG.md
- packages/integration-sveltekit/package.json
- packages/lucia-auth/CHANGELOG.md
- packages/lucia-auth/package.json
This is a pull request automatically created by Auri. You can approve this pull request to update changelogs and publish packages.
- [#392](https://github.com/pilcrowOnPaper/lucia/pull/392) by [@pilcrowOnPaper](https://github.com/pilcrowOnPaper) : [Breaking] Rename type `Configurations` to `Configuration`
[Breaking] Attempting to use an expired key throws `AUTH_EXPIRED_KEY`
- [#392](https://github.com/pilcrowOnPaper/lucia/pull/392) by [@pilcrowOnPaper](https://github.com/pilcrowOnPaper) : Update peer dependency
- [#392](https://github.com/pilcrowOnPaper/lucia/pull/392) by [@pilcrowOnPaper](https://github.com/pilcrowOnPaper) : Update peer dependency
- [#392](https://github.com/pilcrowOnPaper/lucia/pull/392) by [@pilcrowOnPaper](https://github.com/pilcrowOnPaper) : Update peer dependency
- …
> CI: Release

- .auri/$s8hiptn8.md
- packages/adapter-kysely/package.json
- packages/integration-sveltekit/src/server/hooks.ts
- test-apps/sveltekit/package.json
> Fix `handleHooks` type

- .auri/$n58b3dab.md
- packages/integration-oauth/src/providers/discord.ts
Fixed token request for discord oauth provider according to https://stackoverflow.com/a/55391523
> Fixed token request for discord oauth provider

- documentation/collection/main/learn/basics/keys.md
minor grammatical changes to keys documentation
> keys documentation grammar

- .auri/$ttirz0n8.md
- packages/adapter-test/src/database.ts
- packages/lucia-auth/src/auth/index.ts
> Fix adapter config

- packages/lucia-auth/package.json
> Fix package.json

- .auri/$czk56432.md
- documentation/collection/integration/oauth/providers/auth0.md
- documentation/collection/integration/oauth/reference/provider-api.md
- packages/integration-oauth/src/providers/auth0.ts
- packages/integration-oauth/src/providers/index.ts
> Add auth0 oauth provider

- packages/lucia-auth/src/utils/date.ts
Current behavior wouldn't have caused any security issues but for future proofing
> Fix `isWithinExpiration()`

- documentation/build/github.ts
> Show all contributors

- .auri/$2lusrkya.md
- packages/integration-oauth/src/core.ts
- packages/integration-oauth/src/providers/twitch.ts
- packages/integration-oauth/src/request.ts
> Fix Twitch provider

- .auri/$t9fys9d0.md
- packages/adapter-prisma/src/index.ts
> Fix Prisma adapter `setUser()`

- .auri/$u7ipnzy8.md
- packages/adapter-kysely/src/index.ts
> Fix Kysely adapter

- documentation/content/main/start-here/username-password.astro.md
- documentation/content/main/start-here/username-password.nextjs.md
Forgot to fix titles for pages added in #489
> Fix page titles

- .auri/$ukh6m701.md
- documentation/content/main/start-here/getting-started.astro.md
- documentation/content/main/start-here/getting-started.nextjs.md
- documentation/content/main/start-here/introduction.md
- examples/astro-email/README.md
- examples/astro-email/package.json
- examples/astro/README.md
- examples/astro/package.json
- examples/nextjs/README.md
- packages/lucia-auth/src/polyfill/node.ts
- test-apps/astro-email/README.md
- test-apps/astro-email/package.json
- test-apps/astro/README.md
- test-apps/astro/package.json
- test-apps/astro/src/lib/lucia.ts
- test-apps/astro/src/pages/crypto.ts
- test-apps/nextjs/README.md
Astro only partially polyfill `crypto` - see https://github.com/withastro/astro/issues/6870
> Support polyfill for Astro

- .auri/$aawqmvwd.md
- packages/adapter-mongoose/src/index.ts
- packages/adapter-mongoose/test/db.ts
- Fix `Adapter.deleteNonPrimaryKey()` deleting non-primary keys
- Fix `Adapter.updateUserAttributes()` returning old data
> Fix Mongoose adapter

- .auri/$pa8ppjua.md
- packages/lucia-auth/src/scrypt/index.ts
> Remove `console.log()`

- .auri/$8dmu5mpi.md
- packages/adapter-mongoose/src/index.ts
- packages/adapter-mongoose/src/utils.ts
> Use projections in Mongoose adapter

- .auri/$gjrlg0tw.md
> Add PlanetScale changeset

- documentation/content/main/adapters/kysely.md
- documentation/content/main/adapters/planetscale.md
There was some info missing with the planetscaledocs, I've added them and made some improvements so that it easier to follow.
> Improved planetscale docs

- documentation/content/oauth/providers/auth0.md
- documentation/content/oauth/providers/discord.md
- documentation/content/oauth/providers/facebook.md
- documentation/content/oauth/providers/github.md
- documentation/content/oauth/providers/google.md
- documentation/content/oauth/providers/linkedin.md
- documentation/content/oauth/providers/patreon.md
- documentation/content/oauth/providers/reddit.md
- documentation/content/oauth/providers/twitch.md
> Fix each provider's `getAuthorizationUrl()` reference

- documentation/content/oauth/providers/auth0.md
- documentation/content/oauth/providers/discord.md
- documentation/content/oauth/providers/facebook.md
- documentation/content/oauth/providers/github.md
- documentation/content/oauth/providers/google.md
- documentation/content/oauth/providers/linkedin.md
- documentation/content/oauth/providers/patreon.md
- documentation/content/oauth/providers/reddit.md
- documentation/content/oauth/providers/twitch.md
- documentation/content/reference/oauth/oauthprovider.md
Forgot to fix the reference page in #615
> Fix oauth reference

- .auri/$xclxs0s6.md
- packages/lucia-auth/src/middleware/index.ts
> Fix express middleware

- .auri/$7oe1f15h.md
- .auri/$gz64ds0f.md
> Republish packages

- documentation/content/main/adapters/drizzle.md
> Fix drizzle sqlite schema

- documentation/content/tokens/basics/password-tokens.md
Smol typo at https://lucia-auth.com/tokens/basics/password-tokens#initialization
> Fix password tokens code example

- .auri/$onuenc6v.md
> Fix changelog

- .auri/$7oe1f15h.md
- .auri/$8nda6vqj.md
- .auri/$f6ziamic.md
- .auri/$fhi5x1dv.md
- .auri/$gz64ds0f.md
- .auri/$onuenc6v.md
- .auri/$xclxs0s6.md
- packages/adapter-postgresql/CHANGELOG.md
- packages/adapter-postgresql/package.json
- packages/integration-oauth/CHANGELOG.md
- packages/integration-oauth/package.json
- packages/integration-tokens/CHANGELOG.md
- packages/integration-tokens/package.json
- packages/lucia-auth/CHANGELOG.md
- packages/lucia-auth/package.json
Reverts pilcrowOnPaper/lucia#618
> Revert "CI: Release"

- documentation/.prettierignore
- documentation/content/oauth/start-here/getting-started.astro.md
- documentation/content/oauth/start-here/getting-started.nextjs.md
- documentation/content/oauth/start-here/getting-started.remix.md
- examples/astro/src/pages/api/oauth/github.ts
- examples/astro/src/pages/api/oauth/index.ts
- examples/nextjs-app/app/api/oauth/github/route.ts
- examples/nextjs-app/app/api/oauth/route.ts
- examples/nextjs/pages/api/oauth/github.ts
- examples/nextjs/pages/api/oauth/index.ts
- examples/remix/.prettierignore
- examples/remix/app/routes/api.oauth.github.ts
- examples/remix/app/routes/api.oauth.ts
- examples/remix/auth/cookie.server.ts
- examples/sveltekit/src/routes/api/oauth/github/+server.ts
- test-apps/astro/src/pages/api/oauth/github.ts
- test-apps/astro/src/pages/api/oauth/index.ts
- test-apps/nextjs-app/app/api/oauth/github/route.ts
- test-apps/nextjs-app/app/api/oauth/route.ts
- test-apps/nextjs/pages/api/oauth/github.ts
- test-apps/nextjs/pages/api/oauth/index.ts
- test-apps/remix/.prettierignore
- test-apps/remix/app/routes/api.oauth.github.ts
- test-apps/remix/app/routes/api.oauth.ts
- test-apps/remix/auth/cookie.server.ts
- test-apps/sveltekit/src/routes/api/oauth/github/+server.ts
> Add OAuth introduction pages for other frameworks

- documentation/integrations/cela/content.ts
- documentation/src/components/Layout.astro
- Sets framework search params automatically
- Searches for content with different framework id if initial search fails
> Fix accidental 404s when sharing link

- documentation/content/main/start-here/username-password.nuxt.md
> Fix Nuxt tutorial

- documentation/content/main/start-here/username-password.nuxt.md
> Fix broken link

- documentation/content/main/nextjs.nextjs/username-password-example-app-router.md
- documentation/content/main/start-here/username-password.astro.md
- documentation/content/main/start-here/username-password.nextjs.md
- documentation/content/main/start-here/username-password.nuxt.md
- documentation/content/main/start-here/username-password.qwik.md
- documentation/content/main/start-here/username-password.remix.md
- documentation/content/main/start-here/username-password.sveltekit.md
> Docs: Add introductions on cloning projects

- examples/sveltekit/package.json
- packages/lucia-auth/src/auth/request.ts
- test-apps/sveltekit/package.json
Decouples `AuthRequest.validate()` and `AuthRequest.validateUser()`
> Simplify `AuthRequest` methods

- .auri/$2p91cl4y.md
- documentation/content/main/basics/configuration.md
- packages/lucia-auth/package.json
- packages/lucia-auth/src/auth/index.ts
- packages/lucia-auth/src/auth/request.ts
- packages/lucia-auth/src/utils/crypto.ts
- packages/lucia-auth/src/utils/debug.test.ts
- packages/lucia-auth/src/utils/debug.ts
This PR adds an experimental debug mode, enabled with `experimental.debugMode` config.
> Experimental: Debug mode

- .auri/$pqwjf5xz.md
- documentation/content/oauth/providers/google.md
- packages/integration-oauth/src/providers/google.ts
This PR add access type to Google OAuth provider to get refresh_token.
> Add Google OAuth Access type

- .auri/$8p6dcsp7.md
- .auri/$cw05ide3.md
- packages/integration-oauth/src/providers/github.ts
- packages/integration-oauth/src/providers/google.ts
Fixes `GithubUser` and `GoogleUser`
> Fix OAuth provider user type

- documentation/content/main/start-here/username-password.qwik.md
… auth.createSession()
In the current documentation the session object returned from auth.createSession() is wrongfully destructured.
Fixes #697
> Fixes #697

- .auri/$5781xgg9.md
- packages/adapter-prisma/src/prisma.ts
- packages/adapter-prisma/test/index.ts
New:
```ts
const prisma: (client: PrismaClient, options?: {
modelNames: ModelNames,
userRelationKey: string
}) => InitializeAdapter<Adapter>
```
> Update `prisma()` adapter

- .auri/$urtm2qa5.md
- packages/lucia/src/utils/cookie.ts
- packages/lucia/src/utils/index.ts
> Export `parseCookie()`

- .auri/$sn8od9ac.md
- packages/oauth/src/core.ts
- packages/oauth/src/index.ts
- packages/oauth/src/request.ts
Replace `LuciaOAuthRequestError` with new `OAuthRequestError`, which includes a `request` and `response` property
> Update OAuth error

- documentation/content/main/start-here/getting-started.sveltekit.md
> Fix import type in getting-started.sveltekit.md

- packages/oauth/src/providers/linkedin.ts
The LinkedIn provider fails when the user doesn't have a profile picture. This fix resolves issue #742
> fixed linkedin profile picture issue

- packages/oauth/src/providers/linkedin.ts
Reverts pilcrowOnPaper/lucia#743
> Revert "fixed linkedin profile picture issue"

- .auri/$72f6ffrt.md
- documentation-v2/content/oauth/providers/osu.md
- packages/oauth/src/providers/index.ts
- packages/oauth/src/providers/osu.ts
[osu!](https://osu.ppy.sh/home) is a rhythm game. Some developers use its OAuth integration for signing up players to their tournaments and for 3rd party sites for the game.
Added the provider itself and the documentation for it.
> Feature: Add osu! OAuth provider

- documentation-v2/content/main/2.database-adapters/better-sqlite3.md
- documentation-v2/content/main/2.database-adapters/cloudflare-d1.md
- documentation-v2/content/main/2.database-adapters/libsql.md
- documentation-v2/content/main/2.database-adapters/mongoose.md
- documentation-v2/content/main/2.database-adapters/mysql2.md
- documentation-v2/content/main/2.database-adapters/pg.md
- documentation-v2/content/main/2.database-adapters/planetscale-serverless.md
- documentation-v2/content/main/2.database-adapters/postgres.md
- documentation-v2/content/main/2.database-adapters/prisma.md
- documentation/content/reference/oauth/providersession.md
> Update adapter params docs

- .auri/$ftny8ufw.md
- packages/lucia/src/utils/crypto.ts
> Normalize hash before comparison

- .auri/$woxsf5uf.md
- packages/adapter-mysql/package.json
- packages/adapter-mysql/src/drivers/planetscale.ts
- packages/adapter-mysql/src/lucia.d.ts
> Update planetscale types

- .auri/$3qv9gdxj.md
- packages/oauth/src/providers/google.ts
This PR add fixed Google OAuth Access type in OAuth v2 package
> fix: Add Google OAuth Access type

- documentation/src/components/Header.astro
> Remove menu button from blog pages

- .auri/$pf7fuzd7.md
- documentation/content/oauth/providers/google.md
- packages/oauth/src/providers/google.ts
> Fix google user type

- documentation/content/main/0.start-here/0.getting-started/sveltekit.md
> fix: added `export` to auth

- README.md
- documentation/content/main/0.start-here/2.migrate-v2/prisma.md
> Fix prisma migration guide

- documentation/content/main/1.basics/1.users.md
- documentation/content/main/1.basics/2.keys.md
- documentation/content/main/1.basics/5.using-cookies.md
- documentation/content/main/1.basics/6.using-bearer-tokens.md
There should be enough info in the docs to close #824 , even if an overview page wasn't added
> [Docs] Add more info on security

- .auri/$5zlvu8ot.md
- .auri/$m5fgfnep.md
- documentation/content/main/3.extending-lucia/0.database-adapters-api.md
- packages/adapter-prisma/src/prisma.ts
- packages/adapter-test/src/tests/main.ts
- packages/adapter-test/src/tests/session.ts
Updates `@lucia-auth/adapter-prisma` accordingly.
> Add tests to check delete operations don't throw errors if target is invalid

- .auri/$m3rtr8cd.md
- packages/oauth/src/core.ts
- packages/oauth/src/utils.ts
Fixes the `generatePKCECodeChallenge()` function to correctly apply SHA-256 and Base64Url encoding as per PKCE specification.
> fix generatePKCECodeChallenge()

- documentation/src/components/Header.astro
- documentation/vercel.json
Add redirects for routes changed in #965
> Setup redirects

- .auri/$q4pb9pqd.md
- documentation/content/reference/lucia/interfaces/auth.md
> Update key docs

- .auri/$aydq7n8b.md
- packages/oauth/src/providers/atlassian.ts
- packages/oauth/src/providers/index.ts
Planning to work on docs after adding several more providers
> Add Atlassian OAuth provider

- .auri/$ixlmonvt.md
- documentation/content/oauth/providers/discord.md
- packages/oauth/src/providers/discord.ts
Add support for global_name and avatar_decoration fields in DiscordUser type
> [Patch] Update types for Discord

- .auri/$90975ol0.md
- packages/adapter-postgresql/src/drivers/pg.ts
Fix release of connection for transaction in pg
> Fix transaction in pg

- documentation/content/guidebook/drizzle-orm.md
- documentation/content/guidebook/vercel-postgres.md
- documentation/content/main/getting-started/$astro.md
- examples/astro/email-and-password/package.json
- examples/astro/github-oauth/package.json
- examples/astro/username-and-password/package.json
Also for the Drizzle guide too
> Fix typos in Astro docs

- .auri/$z5882a0r.md
- packages/lucia/package.json
- packages/lucia/tsconfig.json
- packages/oauth/package.json
- packages/oauth/tsconfig.json
TS was including `*.test.ts` files in the release.
> Remove test files from release

- README.md
- documentation/content/guidebook/email-verification-codes.md
- documentation/content/guidebook/email-verification-links/$express.md
- documentation/content/guidebook/email-verification-links/$nextjs-app.md
- documentation/content/guidebook/login-throttling.md
> Docs: fix typos

- .auri/$n5h6ktgf.md
- documentation/content/oauth/providers/facebook.md
- packages/oauth/src/providers/facebook.ts
> Add email field to `FacebookUser`

- .auri/$sz2geodk.md
- packages/adapter-session-redis/src/drivers/ioredis.ts
- packages/adapter-session-redis/src/drivers/redis.ts
- packages/adapter-session-redis/src/drivers/upstash.ts
- packages/adapter-session-redis/src/lucia.d.ts
- packages/adapter-session-unstorage/src/unstorage.ts
> Fix Upstash adapter

- .auri/$xny6yl59.md
- documentation/content/oauth/index.md
- documentation/content/oauth/providers/apple.md
- documentation/content/oauth/providers/atlassian.md
- documentation/content/oauth/providers/azure-ad.md
- documentation/content/oauth/providers/bitbucket.md
- documentation/content/oauth/providers/box.md
- documentation/content/oauth/providers/discord.md
- documentation/content/oauth/providers/dropbox.md
- documentation/content/oauth/providers/facebook.md
- documentation/content/oauth/providers/github.md
- documentation/content/oauth/providers/gitlab.md
- documentation/content/oauth/providers/google.md
- documentation/content/oauth/providers/lichess.md
- documentation/content/oauth/providers/line.md
- documentation/content/oauth/providers/linkedin.md
- documentation/content/oauth/providers/osu.md
- documentation/content/oauth/providers/patreon.md
- documentation/content/oauth/providers/reddit.md
- documentation/content/oauth/providers/salesforce.md
- documentation/content/oauth/providers/slack.md
- documentation/content/oauth/providers/spotify.md
- documentation/content/oauth/providers/strava.md
- documentation/content/oauth/providers/twitch.md
- documentation/content/oauth/providers/twitter.md
- packages/oauth/src/providers/cognito.ts
* Cleanup unused `identityProvider` param in the Cognito provider (related to #988)
* Cleanup some docs
> Cleanup unused `identityProvider` param in the Cognito provider

- .auri/$gpv19h52.md
- .auri/$gpv19h5j.md
- documentation/content/oauth/providers/apple.md
- documentation/content/oauth/providers/atlassian.md
- documentation/content/oauth/providers/bitbucket.md
- documentation/content/oauth/providers/box.md
- documentation/content/oauth/providers/cognito.md
- documentation/content/oauth/providers/discord.md
- documentation/content/oauth/providers/dropbox.md
- documentation/content/oauth/providers/facebook.md
- documentation/content/oauth/providers/github.md
- documentation/content/oauth/providers/gitlab.md
- documentation/content/oauth/providers/google.md
- documentation/content/oauth/providers/line.md
- documentation/content/oauth/providers/osu.md
- documentation/content/oauth/providers/patreon.md
- documentation/content/oauth/providers/reddit.md
- documentation/content/oauth/providers/salesforce.md
- documentation/content/oauth/providers/slack.md
- documentation/content/oauth/providers/spotify.md
- documentation/content/oauth/providers/strava.md
- documentation/content/oauth/providers/twitch.md
- examples/nextjs-app/apple-oauth/app/login/apple/callback/route.ts
- packages/oauth/src/providers/apple.ts
* Added scope to Apple oauth config
* Updated Apple AuthUser according to Apple documentation https://developer.apple.com/documentation/sign_in_with_apple/request_an_authorization_to_the_sign_in_with_apple_server
* Updated documentation to match new AuthUser
> Update apple oauth

- .auri/$vhgr4emb.md
- packages/oauth/src/providers/line.ts
Changing this link works correctly for me.
> Fix link at `getLineUser()`

- .auri/$8145tnre.md
- packages/lucia/src/auth/request.ts
> fix: use `reject` instead of `throw`

- .auri/$saog9jyl.md
- packages/oauth/src/providers/slack.ts
With these changes the Slack provider is now working for me - so hopefully I did something right :)
> Fix several issues encountered in the Slack provider

- documentation/content/guidebook/email-verification-links/$nuxt.md
- documentation/content/guidebook/github-oauth/$nuxt.md
- documentation/content/guidebook/sign-in-with-username-and-password/$nuxt.md
This PR updates the `oauth` docs part for Nuxt to align with what exists in the example.
> docs: updated docs for nuxt oauth

- documentation/content/main/basics/using-cookies.md
> Docs: Fix csrf description

- .auri/$87kr76r2.md
- packages/lucia/src/scrypt/MODULE_LICENSE
- packages/lucia/src/scrypt/index.ts
- packages/lucia/src/scrypt/pbkdf.ts
- packages/lucia/src/scrypt/utils.ts
> Add proper attribution for `@noble/hashes`

- .auri/$g7e7prn5.md
- packages/oauth/src/providers/auth0.ts
> Update params `appDomain` for `auth0()`

- .auri/$ymzad0k8.md
- packages/lucia/package.json
- packages/lucia/src/middleware/index.ts
Fixes #1211, as well as another issue with Express and TypeScript
> Remove dev dependencies for typing

- .auri/$15w731jp.md
- documentation/content/guidebook/github-oauth/$express.md
- packages/lucia/src/middleware/index.ts
> Fix `express()` middleware cookies

- .auri/$9ry8sulh.md
- packages/adapter-postgresql/src/drivers/postgres.ts
- packages/adapter-postgresql/src/utils.ts
> Stop escaping table names with a schema defined

- documentation/content/main/basics/database.md
I'm no native English speaker but I think this last sentence was incorrectly constructed. I tweaked it to make it sound more natural. I hope it helps
> docs: make the paragrah clearer

- .auri/$l1wuy8uf.md
- packages/adapter-mongoose/package.json
> Update `@lucia-auth/adapter-mongoose` peer dependency 

- .auri/$9i49vkeh.md
- .auri/$z7910syc.md
- packages/lucia/package.json
- packages/lucia/src/scrypt/index.test.ts
- packages/lucia/src/scrypt/index.ts
- packages/lucia/src/utils/crypto.ts
> Revert #1158

- packages/lucia/src/auth/index.ts
Assuming you didn't intend to change how attributes are passed to getUserAttributes()... Thanks 😄
> v3: Fix getUserAttributes param

- .auri/$ypf7ombn.md
- packages/lucia/src/middleware/index.ts
> Fix `setCookie()` method in SvelteKit middleware

- docs/pages/database/sqlite.md
The exported adapter should be `D1Adapter` instead of `CloudflareD1Adapter`
> Fix SQLite Cloudflare D1 Documentation

- .auri/$vkd6ut3c.md
- packages/adapter-session-redis/src/drivers/ioredis.ts
- packages/adapter-session-redis/src/drivers/redis.ts
- packages/adapter-session-redis/src/drivers/upstash.ts
> Fix Redis adapter expiration

- docs/pages/basics/sessions.md
- docs/pages/guides/email-and-password/password-reset.md
- docs/pages/tutorials/username-and-password/sveltekit.md
some issues I found in the docs
> fix docs errors

- .auri/$6cnv96d7.md
- documentation/content/main/basics/configuration.md
- packages/lucia/src/auth/cookie.ts
> Allow `SameSite=None` session cookies

- docs/pages/guides/validate-session-cookies/hono.md
Hey,
Thank you for your work. 
I followed [the docs about Hono](https://lucia-auth.com/guides/validate-session-cookies/hono) to upgrade to v3 and I found some mistakes 😄
> docs: fix hono middleware docs

- docs/pages/getting-started/astro.md
- docs/pages/getting-started/index.md
- docs/pages/upgrade-v3/index.md
See https://github.com/pilcrowOnPaper/oslo/issues/25
> Add Vite config instruction

- docs/pages/getting-started/astro.md
- docs/pages/getting-started/nuxt.md
- docs/pages/getting-started/solidstart.md
- docs/pages/getting-started/sveltekit.md
- docs/pages/tutorials/github-oauth/nextjs-app.md
- docs/pages/tutorials/github-oauth/nextjs-pages.md
- docs/pages/tutorials/username-and-password/nextjs-app.md
- docs/pages/tutorials/username-and-password/nextjs-pages.md
- docs/pages/upgrade-v3/index.md
- package.json
Fix [#1394](https://github.com/lucia-auth/lucia/issues/1394) and a script
> docs: fix some links in doc

- docs/pages/guides/validate-session-cookies/express.md
Use `lucia.createBlankSessionCookie()` if there is no session.
> docs: fix express example

- docs/pages/tutorials/github-oauth/nuxt.md
- docs/pages/tutorials/username-and-password/nuxt.md
> Fix Nuxt middleware

- packages/adapter-mongodb/CHANGELOG.md
- packages/adapter-mongodb/package.json
- packages/adapter-mongodb/src/index.ts
> Fix Mongoose compatibility issues

- docs/pages/reference/main/DatabaseUser.md
DatabaseUser documentation was duplicate of DatabaseSession. Updated it with correct properties.
> Update DatabaseUser documentation

- docs/pages/guides/email-and-password/email-verification-codes.md
- docs/pages/guides/email-and-password/email-verification-links.md
> Fix `isWithinExpirationDate()`

- docs/pages/database/postgresql.md
> Docs for using drizzle adapter instead of Postgres ones

- docs/pages/tutorials/github-oauth/astro.md
- docs/pages/tutorials/github-oauth/nextjs-app.md
- docs/pages/tutorials/github-oauth/nextjs-pages.md
- docs/pages/tutorials/github-oauth/nuxt.md
- docs/pages/tutorials/github-oauth/sveltekit.md
- docs/pages/tutorials/username-and-password/astro.md
> Fix StackBlitz links

- docs/pages/guides/email-and-password/email-verification-codes.md
> Changed verification code validity to 15 minutes

- docs/pages/guides/oauth/custom-providers.md
See https://github.com/pilcrowOnPaper/oslo/commit/bf068e8e21517d57eec552a396d79dcc1bf95fdd for upstream change of `scope` to `scopes`
> Update custom-providers.md parameter name scopes

- packages/adapter-drizzle/CHANGELOG.md
- packages/adapter-drizzle/package.json
- packages/adapter-drizzle/src/drivers/mysql.ts
> Drizzle SQLite adapter: Revert previous optimization for D1 compatibility

- docs/pages/tutorials/username-and-password/sveltekit.md
No issue created because it's a small fix.
> docs: fix svelte kit user and password tutorial

- .auri/$49d0lzfc.md
- docs/pages/reference/main/Lucia/index.md
- docs/pages/tutorials/github-oauth/sveltekit.md
- packages/adapter-postgresql/CHANGELOG.md
- packages/lucia/src/core.ts
> Add `SameSite=None` option

- docs/pages/getting-started/astro.md
- docs/pages/getting-started/sveltekit.md
- docs/pages/guides/validate-session-cookies/astro.md
- docs/pages/guides/validate-session-cookies/sveltekit.md
> Fix "sure sure" in docs

- .auri/$0g99ie7j.md
- .auri/$r44qejjf.md
- docs/pages/basics/users.md
- docs/pages/guides/email-and-password/2fa.md
- docs/pages/guides/email-and-password/basics.md
- docs/pages/guides/email-and-password/email-verification-codes.md
- docs/pages/guides/email-and-password/email-verification-links.md
- docs/pages/guides/email-and-password/password-reset.md
- docs/pages/guides/oauth/account-linking.md
- docs/pages/guides/oauth/basics.md
- docs/pages/guides/oauth/multiple-providers.md
- docs/pages/reference/main/generateId.md
- docs/pages/reference/main/generateIdFromEntropySize.md
- docs/pages/tutorials/github-oauth/astro.md
- docs/pages/tutorials/github-oauth/nextjs-app.md
- docs/pages/tutorials/github-oauth/nextjs-pages.md
- docs/pages/tutorials/github-oauth/nuxt.md
- docs/pages/tutorials/github-oauth/sveltekit.md
- docs/pages/tutorials/username-and-password/astro.md
- docs/pages/tutorials/username-and-password/nextjs-app.md
- docs/pages/tutorials/username-and-password/nextjs-pages.md
- docs/pages/tutorials/username-and-password/nuxt.md
- docs/pages/tutorials/username-and-password/sveltekit.md
- docs/pages/upgrade-v3/index.md
- packages/lucia/package.json
- packages/lucia/src/core.ts
- packages/lucia/src/crypto.test.ts
- packages/lucia/src/crypto.ts
- packages/lucia/src/index.ts
- Add `generateIdfromEntropySize()`
- Use `generateIdfromEntropySize()` for session IDs
- Recommend `generateIdfromEntropySize()` over `generateId()` in docs
> Better ID generation

- docs/pages/guides/email-and-password/basics.md
- docs/pages/guides/email-and-password/password-reset.md
- docs/pages/tutorials/username-and-password/astro.md
- docs/pages/tutorials/username-and-password/nextjs-app.md
- docs/pages/tutorials/username-and-password/nextjs-pages.md
- docs/pages/tutorials/username-and-password/nuxt.md
- docs/pages/tutorials/username-and-password/sveltekit.md
- docs/pages/upgrade-v3/index.md
Updated the hash options parameters, reflecting the `@node-rs/argon2` API, ref: https://github.com/napi-rs/node-rs/blob/main/packages/argon2/README.md#api
> docs: update password hashing parameters

- docs/pages/guides/email-and-password/email-verification-codes.md
I think you meant to use `databaseCode` instead of `code` in this example.
> Fix example code

- docs/pages/guides/troubleshooting.md
Some people were passing `typeof Lucia` instead of `typeof lucia`
> Update troubleshooting page

- docs/pages/database/prisma.md
> Clarify schema in Prisma docs

- docs/pages/getting-started/astro.md
Remove unused import verifyRequestOrigin
> Docs: Remove unused import

- docs/pages/database/index.md
Add DynamoDB adapter to list of community supported adapters.
> Add DynamoDB adapter to list of community supported adapters

- packages/adapter-drizzle/src/drivers/mysql.ts
- packages/adapter-drizzle/src/drivers/sqlite.ts
> Fix types in Drizzle adapter

- pages/tutorials/google-oauth/sveltekit.md
> Update sveltekit.md undocumented import from arctic

- pages/sessions/basic-api/mysql.md
MySQL full code import attribute is duplicated and incorrect.
> Fix: incorrect attribute on import

- pages/sessions/basic-api/prisma.md
small doc update to correct prisma delete session syntax
> docs: correct prisma delete session syntax

- pages/rate-limit/token-bucket.md
This addresses the point raised in #1778
> fix: correct calculation of `refilledAt`

- pages/rate-limit/token-bucket.md
> Fix token bucket implementation

- pages/sessions/basic-api/drizzle-orm.md
- pages/sessions/basic-api/mysql.md
- pages/sessions/basic-api/postgresql.md
- pages/sessions/basic-api/prisma.md
- pages/sessions/basic-api/redis.md
- pages/sessions/basic-api/sqlite.md
- pages/sessions/cookies/index.md
> Fix db inconsistencies

- pages/sessions/basic.md
- pages/sessions/inactivity-timeout.md
Fixes a few typos and minor inconsistencies
> Sessions pages fix
